<a href="https://colab.research.google.com/github/Sae-11/Pytorch_Practice/blob/main/Part1_practice_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
tensor_2d = torch.randn(5, 3)
tensor_2d

tensor([[ 8.4441e-01,  1.6779e+00,  7.7681e-01],
        [-1.9961e+00, -2.6559e+00,  9.4281e-01],
        [ 1.3103e+00,  2.5496e+00, -1.8231e-03],
        [-7.4466e-01,  1.2965e+00, -2.7794e-01],
        [-6.3692e-02, -2.4189e-01, -7.1081e-01]])

In [4]:
tensor_3d = torch.randn(5, 3, 2)
tensor_3d

tensor([[[-0.2057,  0.3235],
         [ 0.5541, -0.2379],
         [-0.8949,  0.6513]],

        [[-0.4298, -0.2362],
         [-0.3953, -1.4533],
         [ 1.3732, -0.8135]],

        [[ 1.3073, -0.1415],
         [ 1.6296, -0.0701],
         [ 0.5918,  1.0045]],

        [[-0.9557,  1.6391],
         [-0.4404,  0.0520],
         [-0.8349,  0.4175]],

        [[ 1.3044, -0.1024],
         [ 1.7726, -0.8097],
         [ 0.7117, -0.5068]]])

In [7]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
# Reshape and View
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [18]:
my_torch2 = torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
my_torch2 = my_torch2.reshape(-1,2)
my_torch2

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [21]:
my_torch2 = my_torch2.reshape(2,-1)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [23]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
my_torch4 = my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [26]:
#Slices
my_torch6 = torch.arange(10)
my_torch6

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
#Grab specific items
my_torch6[7]

tensor(7)

In [29]:
#Grab a slice
my_torch6 = my_torch6.reshape(5,2)
my_torch6

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [30]:
my_torch6[:,1]

tensor([1, 3, 5, 7, 9])

In [31]:
#Return Column
my_torch6[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])